name: PhantomRider
main: com.example.phantomrider.PhantomRiderPlugin
version: 1.0
api-version: 1.20
depend: [ProtocolLib]
commands:
  summonphantom:
    description: Summons a phantom for the player to ride
    usage: /summonphantom
